"""Sensor definitions and register mappings for Weishaupt WEM.

Based on the Weishaupt CanApiJson protocol mapping table and
Modbus TCP register documentation (manual-wem-modbustcp.pdf).

VG frame format: CM(1B) MI(1B) MX(1B) OX(2B) OS(1B) VS(2B) VA(xB)
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.const import (
    PERCENTAGE,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfPressure,
    UnitOfTemperature,
    UnitOfTime,
)


class WeishauptDeviceGroup(StrEnum):
    """Weishaupt device groups."""

    SG = "sg"  # Systemgerät (System device)
    WTC = "wtc"  # WTC boiler
    HK = "hk"  # Heizkreis (Heating circuit)
    WW = "ww"  # Warmwasser (Domestic hot water) - EM-WW
    SOL = "sol"  # Solar
    KA = "ka"  # Kaskade (Cascade)
    RF = "rf"  # Raumfühler (Room sensor)


@dataclass
class WeishauptSensorDefinition:
    """Definition of a single Weishaupt sensor."""

    key: str  # Unique identifier
    name: str  # Human-readable name
    mi: int  # Module Index
    mx: int  # Member Index / Module Extension
    ox: int  # Object Index
    os: int  # Object Sub-index / Offset
    vs: int  # Value size in bytes
    group: WeishauptDeviceGroup  # Device group
    modbus_reg: str  # Modbus register reference
    device_class: SensorDeviceClass | None = None
    state_class: SensorStateClass | None = None
    unit: str | None = None
    scale: float = 1.0  # Multiply raw value by this to get the actual value
    icon: str | None = None
    value_map: dict[int, str] | None = None  # Map raw values to state strings
    entity_category: str | None = None  # "config" or "diagnostic"
    signed: bool = False  # Whether the value is a signed integer


# ============================================================================
# Value maps for enumeration-type registers
# ============================================================================

BETRIEBSART_VORGABE_MAP = {
    1: "Standby",
    2: "Zeitprogramm 1",
    3: "Zeitprogramm 2",
    4: "Zeitprogramm 3",
    5: "Sommer",
    6: "Komfort",
    7: "Normal",
    8: "Absenk",
}

SOWI_UMSCHALTUNG_MAP = {
    0: "Aus",
    1: "Ein",
}

BETRIEBSART_AKTUELL_MAP = {
    1: "System Standby",
    2: "System Sommer",
    3: "Estrich: Funktionsheizen",
    4: "Estrich: Belegreifheizen",
    5: "Urlaub",
    6: "Zeitprogramm 1",
    7: "Zeitprogramm 2",
    8: "Zeitprogramm 3",
    9: "Sommer",
    10: "Absenk",
    11: "Normal",
    12: "Komfort",
    13: "Standby",
}

STATUS_HK_MAP = {
    1: "Raumfrostschutz",
    2: "Anlagenfrostschutz",
    16: "Eingang H1: Sonder",
    17: "Eingang H1: Komfort",
    18: "Eingang H1: Normal",
    19: "Eingang H1: Absenk",
    20: "Eingang H1: Standby",
    21: "Eingang H1: Not-Aus",
    24: "Party",
    32: "Optimierung",
    33: "Niveauanhebung Außentemperatur",
    48: "ext. Notabnahme",
    49: "ext. Überangebot",
    50: "ext. Heizvorgabe",
    51: "Warmwasservorrang",
    64: "Sommerbetrieb witterungsgeführt",
    65: "Heizgrenze Raum",
    66: "Heizgrenze VL",
    67: "Raumthermostat",
    80: "Komfort",
    81: "Normal",
    82: "Absenken",
    83: "Frost",
    84: "Frostschutz aktiv",
}

SYSTEMBETRIEBSART_MAP = {
    1: "Standby",
    2: "Sommer",
    3: "Automatik",
}

STATUS_WW_MAP = {
    0: "Standby: inaktiv",
    1: "Zeitprogramm – Normal",
    2: "Zeitprogramm – Absenk",
    3: "Warmwasserladung aktiv",
    4: "Service",
    5: "Übertemperatur Alternativenergie",
    6: "Überschuss Alternativenergie",
    7: "Akzeptanz WW Alternativenergie",
    8: "Frostschutz",
    9: "Standby durch Systemprogrammschalter",
    10: "Standby durch Eingang H2",
    12: "Normal durch Eingang H2",
    13: "Absenk durch Eingang H2",
}

BETRIEBSPHASE_WTC_MAP = {
    0: "Normalbetrieb",
    10: "Pumpennachlauf",
    15: "Brennertaktsperre Heizen",
    20: "Sperre Mindestheizleistung",
    24: "Adaption Gasstellglied läuft",
    25: "Verzögerter Heizbetrieb",
    30: "Softstart Warmwasser",
    35: "Abregelfunktion Fernsteuerung",
    40: "Spreizung Vorlauf/Abgas",
    45: "Spreizung Vorlauf/Rücklauf",
    50: "Abregelfunktion Abgastemperatur",
    55: "Abschaltung Fernsteuerung",
    60: "Abschaltung Mindestumlauf",
    70: "SCOT Kalibration läuft",
}

BETRIEBSPHASE_BRENNER_MAP = {
    0: "Brenner aus",
    1: "Vorbelüftung",
    2: "Brenner ein: Steuerbetrieb",
    3: "Brenner ein: Regelbetrieb",
    4: "Nachbelüftung",
}

FOLGEWECHSEL_MAP = {
    0: "normal",
    1: "invertiert",
    2: "zeitlich",
    3: "Betriebsstunden",
}

PUMPE_MAP = {
    0: "Aus",
    1: "Ein",
}


# ============================================================================
# Sensor definitions — SG (Systemgerät) — Modbus 100-155
# ============================================================================

SG_SENSORS: list[WeishauptSensorDefinition] = [
    # --- Heating circuit 1 settings (via SG) ---
    WeishauptSensorDefinition(
        key="sg_betriebsart_hk1_vorgabe",
        name="Betriebsart HK1 Vorgabe",
        mi=0x02,
        mx=0x00,
        ox=0x2533,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="100",
        icon="mdi:thermostat",
        value_map=BETRIEBSART_VORGABE_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_sowi_umschaltung_hk1",
        name="So/Wi Umschaltung HK1",
        mi=0x02,
        mx=0x00,
        ox=0x2582,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="101",
        icon="mdi:sun-snowflake-variant",
        value_map=SOWI_UMSCHALTUNG_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_betriebsart_hk1_aktuell",
        name="Betriebsart HK1 aktuell",
        mi=0x02,
        mx=0x00,
        ox=0x257E,
        os=0x04,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="102",
        icon="mdi:thermostat",
        value_map=BETRIEBSART_AKTUELL_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_status_hk1",
        name="Status HK1",
        mi=0x02,
        mx=0x00,
        ox=0x257E,
        os=0x05,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="103",
        icon="mdi:information-outline",
        value_map=STATUS_HK_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_raumsolltemperatur_komfort",
        name="Raumsolltemperatur Komfort",
        mi=0x02,
        mx=0x00,
        ox=0x253B,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="106",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_raumsolltemperatur_normal",
        name="Raumsolltemperatur Normal",
        mi=0x02,
        mx=0x00,
        ox=0x253A,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="107",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_raumsolltemperatur_absenk",
        name="Raumsolltemperatur Absenk",
        mi=0x02,
        mx=0x00,
        ox=0x2539,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="108",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_raumsolltemperatur_aktuell",
        name="Raumsolltemperatur aktuell",
        mi=0x02,
        mx=0x00,
        ox=0x2558,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="109",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_vorlaufsolltemperatur_komfort",
        name="Vorlaufsolltemperatur Komfort",
        mi=0x02,
        mx=0x00,
        ox=0x256B,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="110",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_vorlaufsolltemperatur_normal",
        name="Vorlaufsolltemperatur Normal",
        mi=0x02,
        mx=0x00,
        ox=0x256A,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="111",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_vorlaufsolltemperatur_absenk",
        name="Vorlaufsolltemperatur Absenk",
        mi=0x02,
        mx=0x00,
        ox=0x2569,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="112",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_vorlaufsolltemperatur_sonderniveau",
        name="Vorlaufsolltemperatur Sonderniveau",
        mi=0x02,
        mx=0x00,
        ox=0x252C,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="113",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_n1_vorgabe_ethernet",
        name="N1-Vorgabe über Ethernet",
        mi=0x01,
        mx=0x00,
        ox=0x27F9,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="114",
        icon="mdi:percent",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="sg_vorlaufsolltemperatur_aktuell",
        name="Vorlaufsolltemperatur aktuell",
        mi=0x02,
        mx=0x00,
        ox=0x2559,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="115",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_vorlaufisttemperatur",
        name="Vorlaufisttemperatur",
        mi=0x02,
        mx=0x00,
        ox=0x2507,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="116",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_plattenwaermetauschertemperatur_b2",
        name="Plattenwärmetauschertemperatur (B2)",
        mi=0x01,
        mx=0x00,
        ox=0x261F,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="117",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_pufferspeicher_temperatur_oben",
        name="Pufferspeicher Temperatur oben",
        mi=0x01,
        mx=0x00,
        ox=0x2560,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="118",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_pufferspeicher_temperatur_unten",
        name="Pufferspeicher Temperatur unten",
        mi=0x01,
        mx=0x00,
        ox=0x2561,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="119",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    # Reg 120-123: Can Open spezifisch (8 bytes) — complex, skip for now
    WeishauptSensorDefinition(
        key="sg_systembetriebsart",
        name="Systembetriebsart",
        mi=0x01,
        mx=0x00,
        ox=0x261E,
        os=0x00,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="124",
        icon="mdi:cog",
        value_map=SYSTEMBETRIEBSART_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_aussentemperatur",
        name="Außentemperatur",
        mi=0x01,
        mx=0x00,
        ox=0x26B1,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="125",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_waermeanforderung_heizung",
        name="Wärmeanforderung Heizung",
        mi=0x01,
        mx=0x00,
        ox=0x259C,
        os=0x01,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="126",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_waermeanforderung_warmwasser",
        name="Wärmeanforderung Warmwasser",
        mi=0x01,
        mx=0x00,
        ox=0x259D,
        os=0x01,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="127",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    # --- Warmwasser via SG (130-137) ---
    WeishauptSensorDefinition(
        key="sg_status_warmwasser",
        name="Status Warmwasser",
        mi=0x03,
        mx=0x00,
        ox=0x2569,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="130",
        icon="mdi:water-boiler",
        value_map=STATUS_WW_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_warmwasser_push",
        name="Warmwasser-Push",
        mi=0x03,
        mx=0x00,
        ox=0x2549,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="131",
        icon="mdi:water-boiler-alert",
        value_map=PUMPE_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_wwsolltemperatur_normal",
        name="WW-Solltemperatur Normal",
        mi=0x03,
        mx=0x00,
        ox=0x2539,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="132",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_wwsolltemperatur_absenk",
        name="WW-Solltemperatur Absenk",
        mi=0x03,
        mx=0x00,
        ox=0x2538,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="133",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_wwsolltemperatur_aktuell",
        name="WW-Solltemperatur aktuell",
        mi=0x03,
        mx=0x00,
        ox=0x252C,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="134",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_warmwassertemperatur",
        name="Warmwassertemperatur",
        mi=0x03,
        mx=0x00,
        ox=0x2529,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="135",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_ruecklauftemperatur_zirkulation",
        name="Rücklauftemperatur Zirkulation",
        mi=0x03,
        mx=0x00,
        ox=0x2557,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="136",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_pumpe_warmwasser",
        name="Pumpe Warmwasser",
        mi=0x03,
        mx=0x00,
        ox=0x2551,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="137",
        icon="mdi:pump",
        value_map=PUMPE_MAP,
    ),
    # --- Kaskade (140-146) ---
    WeishauptSensorDefinition(
        key="sg_folgewechsel",
        name="Folgewechsel",
        mi=0x01,
        mx=0x00,
        ox=0x26E4,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="140",
        icon="mdi:swap-horizontal",
        value_map=FOLGEWECHSEL_MAP,
    ),
    WeishauptSensorDefinition(
        key="sg_wechselzeit",
        name="Wechselzeit",
        mi=0x01,
        mx=0x00,
        ox=0x26E6,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="141",
        icon="mdi:timer",
        unit=UnitOfTime.HOURS,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    WeishauptSensorDefinition(
        key="sg_kaskade_abgleichtemperatur",
        name="Kaskade Abgleichtemperatur",
        mi=0x01,
        mx=0x00,
        ox=0x26FE,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="142",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_kaskade_sollmodulation_hz",
        name="Kaskade Soll-Modulation HZ",
        mi=0x01,
        mx=0x00,
        ox=0x261C,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="143",
        icon="mdi:percent",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="sg_kaskade_sollmodulation_ww",
        name="Kaskade Soll-Modulation WW",
        mi=0x01,
        mx=0x00,
        ox=0x261D,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="144",
        icon="mdi:percent",
        unit=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="sg_kaskade_sollwert_hz",
        name="Kaskade Sollwert HZ",
        mi=0x01,
        mx=0x00,
        ox=0x2612,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="145",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sg_kaskade_sollwert_ww",
        name="Kaskade Sollwert WW",
        mi=0x01,
        mx=0x00,
        ox=0x2613,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="146",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    # --- Fehler/Warnung (121-123) via Reg 120 complex ---
    # Uhrzeit / Datum handled by consolidated sensor (`sg_device_time`)

    # Consolidated device time sensor (combines the separate hour/minute/date registers)
    WeishauptSensorDefinition(
        key="sg_device_time",
        name="Uhrzeit / Datum",
        mi=0x01,
        mx=0x00,
        ox=0x2562,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.SG,
        modbus_reg="150-155",
        device_class=SensorDeviceClass.TIMESTAMP,
        entity_category="diagnostic",
    ),
]


# ============================================================================
# Sensor definitions — WTC (Boiler) — Modbus 160-177
# ============================================================================

WTC_SENSORS: list[WeishauptSensorDefinition] = [
    WeishauptSensorDefinition(
        key="wtc_betriebsphase",
        name="Betriebsphase WTC",
        mi=0x09,
        mx=0x01,
        ox=0x2639,
        os=0x00,
        vs=1,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="160",
        icon="mdi:fire",
        value_map=BETRIEBSPHASE_WTC_MAP,
    ),
    WeishauptSensorDefinition(
        key="wtc_betriebsphase_brenner",
        name="Betriebsphase Brenner",
        mi=0x07,
        mx=0x00,
        ox=0x2541,
        os=0x00,
        vs=1,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="161",
        icon="mdi:fire",
        value_map=BETRIEBSPHASE_BRENNER_MAP,
    ),
    WeishauptSensorDefinition(
        key="wtc_vorlaufsolltemperatur",
        name="WTC Vorlaufsolltemperatur",
        mi=0x07,
        mx=0x00,
        ox=0x2545,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="163",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="wtc_kesseltemperatur",
        name="Kesseltemperatur",
        mi=0x07,
        mx=0x00,
        ox=0x2532,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="164",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="wtc_volumenstrom_vpt",
        name="Volumenstrom VPT",
        mi=0x09,
        mx=0x01,
        ox=0x2613,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="165",
        icon="mdi:water-pump",
        unit="l/h",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    WeishauptSensorDefinition(
        key="wtc_anlagendruck",
        name="Anlagendruck",
        mi=0x09,
        mx=0x01,
        ox=0x2614,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="166",
        device_class=SensorDeviceClass.PRESSURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfPressure.BAR,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="wtc_abgastemperatur",
        name="WTC Abgastemperatur",
        mi=0x07,
        mx=0x00,
        ox=0x2533,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="167",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="wtc_ruecklauftemperatur",
        name="WTC Rücklauftemperatur",
        mi=0x07,
        mx=0x00,
        ox=0x2537,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="168",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="wtc_waermeleistung_vpt",
        name="Wärmeleistung VPT",
        mi=0x09,
        mx=0x01,
        ox=0x2631,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="170_171",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfPower.KILO_WATT,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="wtc_tageswaermemenge_vortag_gesamt",
        name="Tageswärmemenge Vortag Gesamt",
        mi=0x09,
        mx=0x01,
        ox=0x2628,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="172_173",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="wtc_tageswaermemenge_vortag_heizen",
        name="Tageswärmemenge Vortag Heizbetrieb",
        mi=0x09,
        mx=0x01,
        ox=0x2626,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="174_175",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="wtc_tageswaermemenge_vortag_ww",
        name="Tageswärmemenge Vortag Warmwasser",
        mi=0x09,
        mx=0x01,
        ox=0x2627,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.WTC,
        modbus_reg="176_177",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        scale=0.01,
    ),
]


# ============================================================================
# Sensor definitions — HK (Heizkreis / EM-HK) — Modbus 1030-1046
# ============================================================================

HK_SENSORS: list[WeishauptSensorDefinition] = [
    WeishauptSensorDefinition(
        key="hk_betriebsart_vorgabe",
        name="HK Betriebsart Vorgabe",
        mi=0x02,
        mx=0x01,
        ox=0x2533,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1030",
        icon="mdi:thermostat",
        value_map=BETRIEBSART_VORGABE_MAP,
    ),
    WeishauptSensorDefinition(
        key="hk_sowi_umschaltung",
        name="HK So/Wi Umschaltung",
        mi=0x02,
        mx=0x01,
        ox=0x2582,
        os=0x02,
        vs=1,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1031",
        icon="mdi:sun-snowflake-variant",
        value_map=SOWI_UMSCHALTUNG_MAP,
    ),
    WeishauptSensorDefinition(
        key="hk_betriebsart_aktuell",
        name="HK Betriebsart aktuell",
        mi=0x02,
        mx=0x01,
        ox=0x257E,
        os=0x04,
        vs=1,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1032",
        icon="mdi:thermostat",
        value_map=BETRIEBSART_AKTUELL_MAP,
    ),
    WeishauptSensorDefinition(
        key="hk_status",
        name="HK Status",
        mi=0x02,
        mx=0x01,
        ox=0x257E,
        os=0x05,
        vs=1,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1033",
        icon="mdi:information-outline",
        value_map=STATUS_HK_MAP,
    ),
    WeishauptSensorDefinition(
        key="hk_raumsolltemperatur_komfort",
        name="HK Raumsolltemperatur Komfort",
        mi=0x02,
        mx=0x01,
        ox=0x253B,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1036",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_raumsolltemperatur_normal",
        name="HK Raumsolltemperatur Normal",
        mi=0x02,
        mx=0x01,
        ox=0x253A,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1037",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_raumsolltemperatur_absenk",
        name="HK Raumsolltemperatur Absenk",
        mi=0x02,
        mx=0x01,
        ox=0x2539,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1038",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_raumsolltemperatur_aktuell",
        name="HK Raumsolltemperatur aktuell",
        mi=0x02,
        mx=0x01,
        ox=0x2558,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1039",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_vorlaufsolltemperatur_komfort",
        name="HK Vorlaufsolltemperatur Komfort",
        mi=0x02,
        mx=0x01,
        ox=0x256B,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1040",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_vorlaufsolltemperatur_normal",
        name="HK Vorlaufsolltemperatur Normal",
        mi=0x02,
        mx=0x01,
        ox=0x256A,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1041",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_vorlaufsolltemperatur_absenk",
        name="HK Vorlaufsolltemperatur Absenk",
        mi=0x02,
        mx=0x01,
        ox=0x2569,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1042",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_vorlaufsolltemperatur_sonderniveau",
        name="HK Vorlaufsolltemperatur Sonderniveau",
        mi=0x02,
        mx=0x01,
        ox=0x252C,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1043",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_vorlaufsolltemperatur_aktuell",
        name="HK Vorlaufsolltemperatur aktuell",
        mi=0x02,
        mx=0x01,
        ox=0x2559,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1045",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="hk_vorlaufisttemperatur",
        name="HK Vorlaufisttemperatur",
        mi=0x02,
        mx=0x01,
        ox=0x2507,
        os=0x02,
        vs=2,
        group=WeishauptDeviceGroup.HK,
        modbus_reg="1046",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
]


# ============================================================================
# Sensor definitions — SOL (Solar) — Modbus 20-27
# ============================================================================

SOL_SENSORS: list[WeishauptSensorDefinition] = [
    WeishauptSensorDefinition(
        key="sol_kollektortemperatur",
        name="Kollektortemperatur",
        mi=0x04,
        mx=0x00,
        ox=0x2501,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.SOL,
        modbus_reg="20",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sol_speichertemperatur_unten",
        name="Speichertemperatur unten",
        mi=0x04,
        mx=0x00,
        ox=0x2502,
        os=0x00,
        vs=2,
        group=WeishauptDeviceGroup.SOL,
        modbus_reg="21",
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        unit=UnitOfTemperature.CELSIUS,
        scale=0.1,
        signed=True,
    ),
    WeishauptSensorDefinition(
        key="sol_solarertrag_gesamt",
        name="Solarertrag Gesamtzähler",
        mi=0x04,
        mx=0x00,
        ox=0x252B,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.SOL,
        modbus_reg="22_23",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="sol_solarertrag_heute",
        name="Solarertrag heute",
        mi=0x04,
        mx=0x00,
        ox=0x252A,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.SOL,
        modbus_reg="24_25",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        scale=0.01,
    ),
    WeishauptSensorDefinition(
        key="sol_solarertrag_vortag",
        name="Solarertrag Vortag",
        mi=0x04,
        mx=0x00,
        ox=0x2529,
        os=0x02,
        vs=4,
        group=WeishauptDeviceGroup.SOL,
        modbus_reg="26_27",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL,
        unit=UnitOfEnergy.KILO_WATT_HOUR,
        scale=0.01,
    ),
]


# ============================================================================
# All sensor definitions combined
# ============================================================================

ALL_SENSORS: list[WeishauptSensorDefinition] = (
    SG_SENSORS + WTC_SENSORS + HK_SENSORS + SOL_SENSORS
)
